# GitLab CI jobs for Helm deployer

.env: &env
  variables:
    BUILD_PATH: src/helm_deploy

# ============================================================================
# Build Docker development image
# ============================================================================

build:helm_deploy:
  extends: .build_docker
  <<: *env

# ============================================================================
# Test Python package
# ============================================================================

test:helm_deploy:
  extends: .test_python
  <<: *env

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:helm_deploy:
  extends: .publish_docker
  dependencies:
    - build:helm_deploy
  <<: *env
