# GitLab CI jobs for Helm deployer

# ============================================================================
# Build Docker development image
# ============================================================================

build:helm_deploy:
  extends: .build_docker
  variables:
    BUILD_PATH: src/helm_deploy

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:helm_deploy:
  extends: .push_docker_nexus
  dependencies:
    - build:helm_deploy
  variables:
    BUILD_PATH: src/helm_deploy
