# GitLab CI jobs for Helm deployer

# ============================================================================
# Build Docker development image
# ============================================================================

build:helm_deploy:
  extends: .build_docker
  variables:
    BUILD_PATH: src/helm_deploy

### ============================================================================
### Test Docker development images
### ============================================================================
#
test:helm_deploy:
  stage: test
  extends: .test_python
  variables:
    BUILD_PATH: src/helm_deploy
  script:
    - cd $BUILD_PATH
    - python3 setup.py test
    - mv .coverage ../../$CI_JOB_NAME.coverage

# ============================================================================
# Tag and publish Docker image (master only)
# ============================================================================

publish:helm_deploy:
  extends: .push_docker_nexus
  dependencies:
    - build:helm_deploy
  variables:
    BUILD_PATH: src/helm_deploy
